language: rust

rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src

script:
  - cargo build --verbose --all
  - cd test_project
  - cargo build --all
  - cd ..
  - cargo metadata --all-features --format-version 1
  - cargo test --all
