language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src

script:
  - travis-cargo --skip nightly test
  - travis-cargo --only nightly test -- --features clippy
