[package]

name = "racer"
version = "0.0.1"
license = "MIT"
description = "Code completion for Rust"
authors = ["Phil Dawes <phil@phildawes.net>"]

[[bin]]
name = "racer"
path = "src/main.rs"

[lib]
name = "racer"
path = "src/lib.rs"