[package]

name = "racer"
version = "2.0.14"
license = "MIT"
description = "Code completion for Rust"
authors = ["Phil Dawes <phil@phildawes.net>"]
homepage = "https://github.com/racer-rust/racer"
repository = "https://github.com/racer-rust/racer"

[lib]
name = "racer"
path = "src/racer/lib.rs"

[[bin]]
name = "racer"
path = "src/bin/main.rs"
doc = false

[profile.release]
debug = true

[dependencies]
log = "0.4"
rustc-ap-syntax = "133.0.0"
toml = "0.4"
env_logger = "0.5"
clap = "2.19"
lazy_static = "1.0"
humantime = "1.1"

[dev-dependencies]
rand = "0.4"
lazy_static = "1.0"

[features]
nightly = []
clippy = []
