[package]
name = "test-crate3"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
description = "test crate for patch.crates-io"
workspace = ".."

[dependencies.rand]
version = "0.5"
default-features = false
features = []