[package]
name = "test-crate3"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
description = "test crate for extern crate~"
workspace = ".."

[dependencies]
rand = "0.5"
serde = "1.0"
regex = "1.0"

